Feature/login
andersonmlima/viajai pull request #4
Opened 2023-09-24 15:29 UTC by michaelbressiani

2023-09-24 19:48 UTC, reinaldonetof requested changes, later dismissed
- É preciso que a tela tenha a possibilidade de ser scrollable.
- Os text input não estão parecidos com o Figma
- Checar novamente as margens laterais, por favor
- Checar o Design dos botões
- `Esqueceu a senha` está sublinhado no figma
- O nome dos botões estão como "Login"
- Se possível exportar o logo do Google e Facebook do figma e adicionar em seus respectivos botões.

2023-10-03 00:46 UTC, reinaldonetof approved these changes

2023-10-03 00:46 UTC, reinaldonetof commented on ViajAI/Login/LoginViewController.swift
> +//        if emailTextField.text == "meu.email@gmail.com" && passwordTextField.text == "123" {
excluir depois os comentarios que não serão usados

2023-10-03 00:47 UTC, fab2828292 approved these changes

2023-10-03 00:52 UTC, merged